export const labels = {
  "name": "Name",
  "totalSessionsPlayed": "Total Games Played",
  "totalSessionsLost": "Total Games Lost",
  "totalSessionsWon": "Total Games Won",
  "totalChampionKills": "Total Champion Kills",
  "killingSpree": "Killing Spree",
  "totalDamageDealt": "Total Damage Dealt",
  "totalDamageTaken": "Total Damage Taken",
  "mostChampionKillsPerSession": "Highest Kill Count",
  "totalMinionKills": "Total Minion Kills",
  "totalDoubleKills": "Total Double Kills",
  "totalTripleKills": "Total Triple Kills",
  "totalQuadraKills": "Total Quadra Kills",
  "totalPentaKills": "Total Penta Kills",
  "totalDeathsPerSession": "Total Deaths",
  "totalGoldEarned": "Total Gold Earned",
  "totalTurretsKilled": "Total Turrets Killed",
  "totalPhysicalDamageDealt": "Total Physical Damage Dealt",
  "totalMagicDamageDealt": "Total Magic Damage Dealth",
  "totalNeutralMinionsKilled": "Total Neutral Minions Killed",
  "totalAssists": "Total Assists",
  "totalHeal": "Total Healing Done",
  "maxLargestKillingSpree": "Largest Killing Spree",
  "maxLargestCriticalStrike": "Largest Critical Strike",
  "maxChampionsKilled": "Champions Killed",
  "maxNumDeaths": "Number of Deaths",
  "maxTimePlayed": "Hours Played This Season",
  "maxTimeSpentLiving": "Time Spent Living",
  'kda': "Kills/Deaths/Assists Ratio",
  'avgDamageDealt': "Average Damage Dealt",
  'avgMinionKills': "Average Minion Kills",
  'avgDamageTaken': "Average Damage Taken",
  'avgDeaths': "Average Deaths",
  'avgGoldEarned': "Average Gold Earned",
  'avgKills': "Average Kills",
  "avgAssists": "Average Assists"
};
